name: sns_clocked_in
description: SNS Clocked In v2 - Employee time tracking and management system
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.0
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
