name: sns_clocked_in
description: SNS Clocked In v2 - Employee time tracking and management system
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
    - assets/brand/
    - assets/icons/
    - assets/images/

  # Fonts
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
          
flutter_native_splash:
  # Brand background color (light grey-blue)
  color: "#F6F8FB"
  android: true
  ios: true
  web: false

  # For Android < 12 and iOS, this will be used
  image: assets/images/splash_logo.png

  # Android 12+ (includes Android 13/14)
  # Uses smaller, properly scaled logo to avoid oversized appearance
  android_12:
    color: "#F6F8FB"
    image: assets/images/splash_logo_android12.png
    icon_background_color: "#F6F8FB"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_log.png"
  remove_alpha_ios: true
  min_sdk_android: 21
